-- Disposable P0 mechanism fixture only. Never apply to live application tables.
CREATE SCHEMA account_context_p0;
CREATE TABLE account_context_p0.accounts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email text NOT NULL UNIQUE,
 is_enabled boolean NOT NULL DEFAULT true,
 auth_version bigint NOT NULL DEFAULT 1 CHECK (auth_version > 0),
 is_admin boolean NOT NULL DEFAULT false
);
CREATE TABLE account_context_p0.bootstrap_state (
 id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
 first_account_id bigint REFERENCES account_context_p0.accounts(id),
 completed_at timestamptz
);
INSERT INTO account_context_p0.bootstrap_state(id) VALUES (1);
CREATE TABLE account_context_p0.vehicles (
 account_id bigint NOT NULL REFERENCES account_context_p0.accounts(id) ON DELETE CASCADE,
 id bigint GENERATED BY DEFAULT AS IDENTITY,
 name text NOT NULL,
 PRIMARY KEY(account_id, id)
);
CREATE TABLE account_context_p0.ledger (
 account_id bigint NOT NULL REFERENCES account_context_p0.accounts(id) ON DELETE CASCADE,
 id bigint GENERATED BY DEFAULT AS IDENTITY,
 vehicle_id bigint,
 note text NOT NULL,
 PRIMARY KEY(account_id, id),
 FOREIGN KEY(account_id, vehicle_id) REFERENCES account_context_p0.vehicles(account_id,id)
 ON DELETE SET NULL (vehicle_id)
);
CREATE SCHEMA odograph_internal;
CREATE TABLE odograph_internal.managed_role_state (
 id smallint PRIMARY KEY CHECK (id = 1),
 contract_version text NOT NULL CHECK (contract_version = 'p0-v1'),
 owner_role text NOT NULL CHECK (owner_role = 'odograph_migrate'),
 installation_id uuid NOT NULL,
 runtime_password text NOT NULL,
 control_password text NOT NULL
);
CREATE TABLE odograph_internal.recovery_metadata (
 id smallint PRIMARY KEY CHECK (id = 1),
 contract_version text NOT NULL CHECK (contract_version = 'p0-v1'),
 owner_role text NOT NULL CHECK (owner_role = 'odograph_migrate'),
 installation_id uuid NOT NULL
);
-- Trusted fixture setup may issue one-time authorizations to prove the M2 seam.
CREATE TABLE odograph_internal.provision_authorizations (
 id uuid PRIMARY KEY,
 account_id bigint UNIQUE REFERENCES account_context_p0.accounts(id)
);
