-- The application remains single-account until all user-owned data has an
-- account boundary. The unique constant-expression index makes that a
-- database invariant while keeping a bigint identity suitable for later
-- multi-user work.
CREATE TABLE accounts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text NOT NULL,
    password_hash text NOT NULL,
    is_admin      boolean NOT NULL DEFAULT true CHECK (is_admin),
    is_enabled    boolean NOT NULL DEFAULT true,
    auth_version  bigint NOT NULL DEFAULT 1 CHECK (auth_version > 0),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CHECK (email = lower(btrim(email)))
);

CREATE UNIQUE INDEX accounts_email_idx ON accounts (email);
CREATE UNIQUE INDEX accounts_singleton_idx ON accounts ((true));

INSERT INTO accounts (
    id, email, password_hash, is_admin, is_enabled, auth_version,
    created_at, updated_at
)
SELECT
    1, lower(btrim(email)), password_hash, true, true, 1,
    created_at, updated_at
FROM local_admin;

SELECT setval(
    pg_get_serial_sequence('accounts', 'id'),
    COALESCE((SELECT max(id) FROM accounts), 1),
    EXISTS (SELECT 1 FROM accounts)
);

DROP TABLE local_admin;
