CREATE TABLE oidc_identities (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            bigint NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    issuer                text NOT NULL,
    subject               text NOT NULL,
    provider_email        text,
    provider_display_name text,
    linked_at             timestamptz NOT NULL DEFAULT now(),
    last_used_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (issuer <> ''),
    CHECK (issuer = rtrim(issuer, '/')),
    CHECK (subject <> ''),
    UNIQUE (issuer, subject),
    UNIQUE (account_id, issuer)
);
