-- The Python preflight runs before this file under the same migration lock and
-- transaction. It refuses accountless personal history and inconsistent links.
CREATE TABLE reference_mileage_rates (
    year int PRIMARY KEY,
    rate_per_mi numeric NOT NULL CHECK (rate_per_mi > 0),
    rate_h2_per_mi numeric CHECK (rate_h2_per_mi > 0),
    h2_start_month smallint CHECK (h2_start_month BETWEEN 1 AND 12),
    CHECK ((rate_h2_per_mi IS NULL) = (h2_start_month IS NULL))
);
INSERT INTO reference_mileage_rates (year, rate_per_mi)
VALUES (2025, 0.7000), (2026, 0.7250);

CREATE TABLE instance_state (
    id smallint PRIMARY KEY CHECK (id = 1),
    first_account_id bigint REFERENCES accounts(id) ON DELETE RESTRICT,
    bootstrap_completed_at timestamptz,
    legacy_config_imported_at timestamptz,
    security_contract_version text NOT NULL DEFAULT 'ownership-prepared-v1'
        CHECK (security_contract_version = 'ownership-prepared-v1'),
    CHECK ((first_account_id IS NULL) = (bootstrap_completed_at IS NULL))
);
INSERT INTO instance_state (id, first_account_id, bootstrap_completed_at)
SELECT 1, (SELECT id FROM accounts), (SELECT created_at FROM accounts);

CREATE TABLE tracking_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    label text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (account_id, id)
);
CREATE TABLE tracking_device_aliases (
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    original_label text NOT NULL,
    tracking_device_id bigint NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    PRIMARY KEY (account_id, original_label),
    FOREIGN KEY (account_id, tracking_device_id)
        REFERENCES tracking_devices(account_id, id) ON DELETE RESTRICT
);
CREATE TABLE ingest_credentials (
    public_id text PRIMARY KEY,
    basic_username text NOT NULL UNIQUE,
    secret_hash text NOT NULL,
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    tracking_device_id bigint,
    kind text NOT NULL CHECK (kind IN ('legacy', 'device')),
    generation bigint NOT NULL DEFAULT 1 CHECK (generation > 0),
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (account_id, tracking_device_id)
        REFERENCES tracking_devices(account_id, id) ON DELETE RESTRICT,
    CHECK ((kind = 'legacy') = (tracking_device_id IS NULL))
);
CREATE INDEX ingest_credentials_account_device_idx
    ON ingest_credentials (account_id, tracking_device_id);

CREATE TABLE account_settings (
    account_id bigint PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    display_tz text NOT NULL DEFAULT 'UTC',
    auto_assign_default_vehicle boolean NOT NULL DEFAULT false,
    ntfy_topic text NOT NULL DEFAULT '',
    nudge_weekly_hour smallint NOT NULL DEFAULT 18 CHECK (nudge_weekly_hour BETWEEN 0 AND 23),
    odometer_reminder_requested boolean NOT NULL DEFAULT false,
    odometer_reminder_hour smallint NOT NULL DEFAULT 9 CHECK (odometer_reminder_hour BETWEEN 0 AND 23),
    email_to text NOT NULL DEFAULT '',
    email_weekly_nudge boolean NOT NULL DEFAULT false,
    email_monthly_summary boolean NOT NULL DEFAULT false,
    email_filing_reminder boolean NOT NULL DEFAULT false,
    email_odometer_reminder boolean NOT NULL DEFAULT false,
    email_digest_hour smallint NOT NULL DEFAULT 9 CHECK (email_digest_hour BETWEEN 0 AND 23),
    email_filing_reminder_mmdd text NOT NULL DEFAULT '01-15',
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO account_settings (account_id, auto_assign_default_vehicle, updated_at)
SELECT a.id, s.auto_assign_default_vehicle, s.updated_at
FROM accounts a CROSS JOIN app_settings s;
DROP TABLE app_settings;

CREATE TEMP TABLE ownership_legacy_checkpoint ON COMMIT DROP AS
SELECT last_run_at, detector_version FROM detector_state;
DROP TABLE detector_state;
CREATE TABLE detector_state (
    account_id bigint NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    tracking_device_id bigint PRIMARY KEY,
    last_run_at timestamptz,
    detector_version int NOT NULL DEFAULT 0,
    FOREIGN KEY (account_id, tracking_device_id)
        REFERENCES tracking_devices(account_id, id) ON DELETE RESTRICT
);

-- Canonical empty-instance seeds become defaults only after an account exists.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM accounts) THEN
        DELETE FROM tag_rules;
        DELETE FROM vehicles;
        DELETE FROM mileage_rates;
    END IF;
END $$;

DO $$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'raw_messages', 'points', 'stays', 'trips', 'places', 'tag_rules',
        'geocode_cache', 'trip_boundary_overrides', 'vehicles',
        'odometer_readings', 'expenses', 'mileage_rates',
        'nudge_delivery_windows', 'odometer_reminder_windows', 'email_deliveries'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ADD COLUMN account_id bigint', table_name);
        EXECUTE format('UPDATE %I SET account_id = (SELECT id FROM accounts)', table_name);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN account_id SET NOT NULL', table_name);
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE',
                       table_name, table_name || '_account_id_fkey');
    END LOOP;
END $$;

ALTER TABLE raw_messages ADD COLUMN tracking_device_id bigint;
ALTER TABLE points ADD COLUMN tracking_device_id bigint;
ALTER TABLE stays ADD COLUMN tracking_device_id bigint;
ALTER TABLE trips ADD COLUMN tracking_device_id bigint;
ALTER TABLE trip_boundary_overrides ADD COLUMN tracking_device_id bigint;

INSERT INTO tracking_devices (account_id, label)
SELECT a.id, streams.device FROM accounts a CROSS JOIN (
    SELECT device FROM points
    UNION SELECT device FROM stays
    UNION SELECT device FROM trips WHERE source = 'detected' AND NOT imported
    UNION SELECT device FROM trip_boundary_overrides
) streams ORDER BY streams.device;
INSERT INTO tracking_device_aliases (account_id, original_label, tracking_device_id)
SELECT account_id, label, id FROM tracking_devices;
INSERT INTO detector_state (account_id, tracking_device_id, last_run_at, detector_version)
SELECT d.account_id, d.id, s.last_run_at, s.detector_version
FROM tracking_devices d CROSS JOIN ownership_legacy_checkpoint s;

UPDATE points p SET tracking_device_id = d.id FROM tracking_devices d
WHERE p.account_id = d.account_id AND p.device = d.label;
UPDATE stays s SET tracking_device_id = d.id FROM tracking_devices d
WHERE s.account_id = d.account_id AND s.device = d.label;
UPDATE trips t SET tracking_device_id = d.id FROM tracking_devices d
WHERE t.account_id = d.account_id AND t.device = d.label
    AND t.source = 'detected' AND NOT t.imported;
UPDATE trip_boundary_overrides o SET tracking_device_id = d.id FROM tracking_devices d
WHERE o.account_id = d.account_id AND o.device = d.label;
ALTER TABLE points ALTER COLUMN tracking_device_id SET NOT NULL;
ALTER TABLE stays ALTER COLUMN tracking_device_id SET NOT NULL;
ALTER TABLE trip_boundary_overrides ALTER COLUMN tracking_device_id SET NOT NULL;
ALTER TABLE trips ADD CONSTRAINT trips_detected_device_check
    CHECK (source <> 'detected' OR imported OR tracking_device_id IS NOT NULL);

DO $$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'raw_messages', 'points', 'stays', 'trips', 'trip_boundary_overrides'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (account_id, tracking_device_id) REFERENCES tracking_devices(account_id, id) ON DELETE RESTRICT',
                       table_name, table_name || '_owned_device_fkey');
    END LOOP;
    FOREACH table_name IN ARRAY ARRAY['places', 'vehicles', 'trips', 'points'] LOOP
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I UNIQUE (account_id, id)',
                       table_name, table_name || '_account_id_id_key');
    END LOOP;
END $$;
ALTER TABLE trips ADD CONSTRAINT trips_owned_stream_id_key UNIQUE (account_id, tracking_device_id, id);
ALTER TABLE points ADD CONSTRAINT points_owned_stream_id_key UNIQUE (account_id, tracking_device_id, id);

ALTER TABLE points DROP CONSTRAINT points_trip_id_fkey;
ALTER TABLE points ADD CONSTRAINT points_owned_trip_fkey
    FOREIGN KEY (account_id, tracking_device_id, trip_id)
    REFERENCES trips(account_id, tracking_device_id, id) ON DELETE SET NULL (trip_id);
ALTER TABLE trip_boundary_overrides DROP CONSTRAINT trip_boundary_overrides_point_id_fkey;
ALTER TABLE trip_boundary_overrides ADD CONSTRAINT trip_boundary_overrides_owned_point_fkey
    FOREIGN KEY (account_id, tracking_device_id, point_id)
    REFERENCES points(account_id, tracking_device_id, id) ON DELETE RESTRICT;
ALTER TABLE trips DROP CONSTRAINT trips_start_place_id_fkey;
ALTER TABLE trips DROP CONSTRAINT trips_end_place_id_fkey;
ALTER TABLE trips DROP CONSTRAINT trips_vehicle_id_fkey;
ALTER TABLE trips ADD CONSTRAINT trips_owned_start_place_fkey
    FOREIGN KEY (account_id, start_place_id) REFERENCES places(account_id, id)
    ON DELETE SET NULL (start_place_id);
ALTER TABLE trips ADD CONSTRAINT trips_owned_end_place_fkey
    FOREIGN KEY (account_id, end_place_id) REFERENCES places(account_id, id)
    ON DELETE SET NULL (end_place_id);
ALTER TABLE trips ADD CONSTRAINT trips_owned_vehicle_fkey
    FOREIGN KEY (account_id, vehicle_id) REFERENCES vehicles(account_id, id)
    ON DELETE SET NULL (vehicle_id);
ALTER TABLE tag_rules DROP CONSTRAINT tag_rules_a_place_fkey;
ALTER TABLE tag_rules DROP CONSTRAINT tag_rules_b_place_fkey;
ALTER TABLE tag_rules ADD CONSTRAINT tag_rules_owned_a_place_fkey
    FOREIGN KEY (account_id, a_place) REFERENCES places(account_id, id) ON DELETE CASCADE;
ALTER TABLE tag_rules ADD CONSTRAINT tag_rules_owned_b_place_fkey
    FOREIGN KEY (account_id, b_place) REFERENCES places(account_id, id) ON DELETE CASCADE;
ALTER TABLE expenses DROP CONSTRAINT expenses_vehicle_id_fkey;
ALTER TABLE expenses DROP CONSTRAINT expenses_trip_id_fkey;
ALTER TABLE expenses ADD CONSTRAINT expenses_owned_vehicle_fkey
    FOREIGN KEY (account_id, vehicle_id) REFERENCES vehicles(account_id, id) ON DELETE RESTRICT;
ALTER TABLE expenses ADD CONSTRAINT expenses_owned_trip_fkey
    FOREIGN KEY (account_id, trip_id) REFERENCES trips(account_id, id) ON DELETE SET NULL (trip_id);
ALTER TABLE odometer_readings DROP CONSTRAINT odometer_readings_vehicle_id_fkey;
ALTER TABLE odometer_readings ADD CONSTRAINT odometer_readings_owned_vehicle_fkey
    FOREIGN KEY (account_id, vehicle_id) REFERENCES vehicles(account_id, id) ON DELETE CASCADE;

ALTER TABLE points DROP CONSTRAINT points_device_recorded_at_key;
ALTER TABLE points ADD CONSTRAINT points_tracking_device_recorded_at_key
    UNIQUE (tracking_device_id, recorded_at);
ALTER TABLE places DROP CONSTRAINT places_name_key;
ALTER TABLE places ADD CONSTRAINT places_account_name_key UNIQUE (account_id, name);
DROP INDEX vehicles_one_default_idx;
CREATE UNIQUE INDEX vehicles_one_default_idx ON vehicles (account_id) WHERE is_default;
ALTER TABLE mileage_rates DROP CONSTRAINT mileage_rates_pkey;
ALTER TABLE mileage_rates ADD PRIMARY KEY (account_id, year);
ALTER TABLE mileage_rates ALTER COLUMN rate_per_mi TYPE numeric;
ALTER TABLE mileage_rates ALTER COLUMN rate_h2_per_mi TYPE numeric;
ALTER TABLE geocode_cache DROP CONSTRAINT geocode_cache_pkey;
ALTER TABLE geocode_cache ADD PRIMARY KEY (account_id, lat, lon);
ALTER TABLE nudge_delivery_windows DROP CONSTRAINT nudge_delivery_windows_pkey;
ALTER TABLE nudge_delivery_windows ADD PRIMARY KEY (account_id, window_ends_at);
ALTER TABLE odometer_reminder_windows DROP CONSTRAINT odometer_reminder_windows_pkey;
ALTER TABLE odometer_reminder_windows ADD PRIMARY KEY (account_id, quarter_starts_at);
ALTER TABLE email_deliveries DROP CONSTRAINT email_deliveries_pkey;
ALTER TABLE email_deliveries ADD PRIMARY KEY (account_id, kind, period_end);
DROP INDEX trip_boundary_overrides_device_idx;
DROP INDEX trip_boundary_overrides_suppress_range_idx;
DROP INDEX trip_boundary_overrides_range_idx;
CREATE INDEX trip_boundary_overrides_device_idx ON trip_boundary_overrides (account_id, tracking_device_id);
CREATE UNIQUE INDEX trip_boundary_overrides_suppress_range_idx
    ON trip_boundary_overrides (tracking_device_id, range_start, range_end) WHERE kind = 'suppress';
CREATE UNIQUE INDEX trip_boundary_overrides_range_idx
    ON trip_boundary_overrides (tracking_device_id, kind, range_start, range_end) WHERE range_start IS NOT NULL;
CREATE INDEX trips_account_started_at_idx ON trips (account_id, started_at DESC, id DESC);
CREATE INDEX points_account_device_recorded_at_idx ON points (account_id, tracking_device_id, recorded_at);
CREATE INDEX stays_account_device_ended_at_idx ON stays (account_id, tracking_device_id, ended_at DESC);
CREATE INDEX raw_messages_account_received_at_idx ON raw_messages (account_id, received_at);
CREATE INDEX expenses_account_date_idx ON expenses (account_id, incurred_on DESC, id DESC);
CREATE INDEX odometer_readings_account_vehicle_idx ON odometer_readings (account_id, vehicle_id, recorded_at);
