ALTER TABLE public.accounts ADD COLUMN email_verified_at timestamptz;

CREATE TABLE public.email_challenges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
    purpose text NOT NULL CHECK (purpose IN ('verify_current', 'change_email')),
    target_email text NOT NULL CHECK (target_email = lower(btrim(target_email)) AND target_email <> ''),
    issued_email text NOT NULL,
    issued_auth_version bigint NOT NULL CHECK (issued_auth_version > 0),
    token_digest text NOT NULL UNIQUE CHECK (token_digest ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    revoked_at timestamptz,
    failed_attempts smallint NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    CHECK (expires_at > created_at),
    CHECK (consumed_at IS NULL OR revoked_at IS NULL)
);
CREATE UNIQUE INDEX email_challenges_one_live_idx ON public.email_challenges (account_id, purpose)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;
CREATE INDEX email_challenges_issue_limit_idx ON public.email_challenges (account_id, created_at);

-- Challenge rows are protected account data. Runtime has an account policy
-- for defense in depth but receives no table grant; control uses guarded functions.
ALTER TABLE public.email_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_challenges FORCE ROW LEVEL SECURITY;

CREATE FUNCTION public.issue_email_challenge(
    input_account_id bigint, input_auth_version bigint, input_purpose text,
    input_target_email text, input_token_digest text
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
DECLARE
    account_row public.accounts%ROWTYPE;
    target_email text := lower(btrim(input_target_email));
    issued_at timestamptz;
BEGIN
    IF input_purpose NOT IN ('verify_current', 'change_email')
       OR input_target_email IS NULL OR target_email = ''
       OR input_token_digest IS NULL OR input_token_digest !~ '^[0-9a-f]{64}$' THEN
        RETURN false;
    END IF;
    SELECT * INTO account_row FROM public.accounts WHERE id = input_account_id FOR UPDATE;
    IF NOT FOUND OR NOT account_row.is_enabled OR account_row.auth_version <> input_auth_version
       OR account_row.password_hash = ''
       OR (input_purpose = 'verify_current' AND target_email <> account_row.email)
       OR (input_purpose = 'change_email' AND target_email = account_row.email) THEN
        RETURN false;
    END IF;
    issued_at := pg_catalog.clock_timestamp();
    IF EXISTS (SELECT 1 FROM public.email_challenges
               WHERE account_id = input_account_id AND created_at > issued_at - interval '1 minute')
       OR (SELECT count(*) FROM public.email_challenges
           WHERE account_id = input_account_id AND created_at > issued_at - interval '24 hours') >= 5 THEN
        RETURN false;
    END IF;
    UPDATE public.email_challenges SET revoked_at = issued_at
    WHERE account_id = input_account_id AND purpose = input_purpose
      AND consumed_at IS NULL AND revoked_at IS NULL;
    INSERT INTO public.email_challenges
        (account_id, purpose, target_email, issued_email, issued_auth_version,
         token_digest, created_at, expires_at)
    VALUES (input_account_id, input_purpose, target_email, account_row.email,
            account_row.auth_version, input_token_digest, issued_at, issued_at + interval '30 minutes');
    RETURN true;
END
$body$;

CREATE FUNCTION public.revoke_email_challenge(
    input_account_id bigint, input_purpose text, input_token_digest text
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
BEGIN
    UPDATE public.email_challenges SET revoked_at = pg_catalog.clock_timestamp()
    WHERE account_id = input_account_id AND purpose = input_purpose
      AND token_digest = input_token_digest AND consumed_at IS NULL AND revoked_at IS NULL;
END
$body$;

CREATE FUNCTION public.consume_email_challenge(
    input_account_id bigint, input_auth_version bigint, input_purpose text,
    input_token_digest text
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
DECLARE
    account_row public.accounts%ROWTYPE;
    challenge_row public.email_challenges%ROWTYPE;
    checked_at timestamptz;
BEGIN
    IF input_purpose NOT IN ('verify_current', 'change_email')
       OR input_token_digest IS NULL OR input_token_digest !~ '^[0-9a-f]{64}$' THEN
        RETURN false;
    END IF;
    SELECT * INTO account_row FROM public.accounts WHERE id = input_account_id FOR UPDATE;
    IF NOT FOUND OR NOT account_row.is_enabled OR account_row.auth_version <> input_auth_version THEN
        RETURN false;
    END IF;
    SELECT * INTO challenge_row FROM public.email_challenges
    WHERE account_id = input_account_id AND purpose = input_purpose
      AND consumed_at IS NULL AND revoked_at IS NULL FOR UPDATE;
    IF NOT FOUND THEN
        RETURN false;
    END IF;
    checked_at := pg_catalog.clock_timestamp();
    IF challenge_row.expires_at <= checked_at OR challenge_row.failed_attempts >= 5
       OR challenge_row.issued_email <> account_row.email
       OR challenge_row.issued_auth_version <> account_row.auth_version THEN
        RETURN false;
    END IF;
    IF challenge_row.token_digest <> input_token_digest THEN
        UPDATE public.email_challenges SET failed_attempts = failed_attempts + 1
        WHERE id = challenge_row.id;
        RETURN false;
    END IF;
    IF input_purpose = 'verify_current' THEN
        IF challenge_row.target_email <> account_row.email THEN
            RETURN false;
        END IF;
        UPDATE public.accounts SET email_verified_at = checked_at, updated_at = checked_at
        WHERE id = input_account_id;
    ELSE
        IF challenge_row.target_email = account_row.email
           OR EXISTS (SELECT 1 FROM public.accounts WHERE email = challenge_row.target_email) THEN
            RETURN false;
        END IF;
        BEGIN
            UPDATE public.accounts SET email = challenge_row.target_email,
                email_verified_at = checked_at, auth_version = auth_version + 1,
                updated_at = checked_at WHERE id = input_account_id;
        EXCEPTION WHEN unique_violation THEN
            RETURN false;
        END;
    END IF;
    UPDATE public.email_challenges SET consumed_at = checked_at WHERE id = challenge_row.id;
    RETURN true;
END
$body$;

REVOKE ALL ON FUNCTION public.issue_email_challenge(bigint,bigint,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.revoke_email_challenge(bigint,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consume_email_challenge(bigint,bigint,text,text) FROM PUBLIC;

DO $$
BEGIN
    IF to_regclass('odograph_service.managed_role_state') IS NOT NULL THEN
        CREATE POLICY account_isolation ON public.email_challenges FOR ALL TO odograph_runtime
            USING (account_id = NULLIF(current_setting('app.account_id', true), '')::bigint)
            WITH CHECK (account_id = NULLIF(current_setting('app.account_id', true), '')::bigint);
        CREATE POLICY bootstrap_defaults ON public.email_challenges FOR ALL TO odograph_bootstrap
            USING (true) WITH CHECK (true);
        ALTER TABLE public.email_challenges OWNER TO odograph_migrate;
        ALTER SEQUENCE public.email_challenges_id_seq OWNER TO odograph_migrate;
        REVOKE ALL ON public.email_challenges FROM PUBLIC, odograph_control, odograph_runtime, odograph_bootstrap;
        REVOKE ALL ON SEQUENCE public.email_challenges_id_seq FROM PUBLIC, odograph_control, odograph_runtime, odograph_bootstrap;
        GRANT SELECT, INSERT, UPDATE ON public.email_challenges TO odograph_bootstrap;
        GRANT USAGE ON SEQUENCE public.email_challenges_id_seq TO odograph_bootstrap;
        REVOKE UPDATE ON public.accounts FROM odograph_control;
        GRANT UPDATE (password_hash, is_enabled, auth_version, updated_at,
                      avatar_bytes, avatar_mime, avatar_updated_at) ON public.accounts TO odograph_control;
        ALTER FUNCTION public.issue_email_challenge(bigint,bigint,text,text,text) OWNER TO odograph_bootstrap;
        ALTER FUNCTION public.revoke_email_challenge(bigint,text,text) OWNER TO odograph_bootstrap;
        ALTER FUNCTION public.consume_email_challenge(bigint,bigint,text,text) OWNER TO odograph_bootstrap;
        GRANT EXECUTE ON FUNCTION public.issue_email_challenge(bigint,bigint,text,text,text) TO odograph_control;
        GRANT EXECUTE ON FUNCTION public.revoke_email_challenge(bigint,text,text) TO odograph_control;
        GRANT EXECUTE ON FUNCTION public.consume_email_challenge(bigint,bigint,text,text) TO odograph_control;
    END IF;
END $$;
