CREATE TABLE public.account_security_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    actor_account_id bigint NOT NULL,
    target_account_id bigint NOT NULL,
    action text NOT NULL CHECK (action <> '' AND char_length(action) <= 64),
    outcome text NOT NULL CHECK (outcome <> '' AND char_length(outcome) <= 64)
);
CREATE INDEX account_security_audit_time_idx
    ON public.account_security_audit (occurred_at, id);

-- Protected account state transitions and security audit access.
CREATE OR REPLACE FUNCTION public.admin_set_account_enabled(
    input_actor_id bigint, input_actor_auth_version bigint,
    input_target_id bigint, input_enable boolean
) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
DECLARE
    actor_row public.accounts%ROWTYPE;
    target_row public.accounts%ROWTYPE;
    changed_at timestamptz;
    result text;
BEGIN
    IF input_actor_id IS NULL OR input_actor_auth_version IS NULL
       OR input_target_id IS NULL OR input_enable IS NULL
       OR input_actor_id = input_target_id THEN
        RAISE EXCEPTION 'account transition unavailable' USING ERRCODE = '42501';
    END IF;

    PERFORM pg_catalog.pg_advisory_xact_lock(901412, 1);
    PERFORM 1 FROM public.accounts
    WHERE id IN (input_actor_id, input_target_id) ORDER BY id FOR UPDATE;
    SELECT * INTO actor_row FROM public.accounts WHERE id = input_actor_id;
    SELECT * INTO target_row FROM public.accounts WHERE id = input_target_id;
    IF actor_row.id IS NULL OR NOT actor_row.is_admin OR NOT actor_row.is_enabled
       OR actor_row.auth_version <> input_actor_auth_version
       OR target_row.id IS NULL THEN
        RAISE EXCEPTION 'account transition unavailable' USING ERRCODE = '42501';
    END IF;
    IF target_row.is_enabled = input_enable THEN
        IF input_enable THEN
            result := 'already_enabled';
        ELSE
            result := 'already_disabled';
        END IF;
        INSERT INTO public.account_security_audit
            (occurred_at, actor_account_id, target_account_id, action, outcome)
        VALUES (pg_catalog.clock_timestamp(), input_actor_id, input_target_id,
                CASE WHEN input_enable THEN 'enable_account' ELSE 'disable_account' END,
                result);
        RETURN result;
    END IF;
    IF NOT input_enable AND target_row.is_admin AND NOT EXISTS (
        SELECT 1 FROM public.accounts a
        WHERE a.id <> input_target_id AND a.is_admin AND a.is_enabled
          AND (NULLIF(a.password_hash, '') IS NOT NULL OR EXISTS (
              SELECT 1 FROM public.oidc_identities oi WHERE oi.account_id = a.id
          ))
    ) THEN
        RAISE EXCEPTION 'account transition unavailable' USING ERRCODE = '42501';
    END IF;

    changed_at := pg_catalog.clock_timestamp();
    IF input_enable THEN
        UPDATE public.accounts SET is_enabled = true, updated_at = changed_at
        WHERE id = input_target_id;
        result := 'enabled';
    ELSE
        UPDATE public.accounts SET is_enabled = false,
            auth_version = auth_version + 1, updated_at = changed_at
        WHERE id = input_target_id;
        UPDATE public.email_challenges SET revoked_at = changed_at
        WHERE account_id = input_target_id
          AND consumed_at IS NULL AND revoked_at IS NULL;
        DELETE FROM public.oidc_action_proofs WHERE account_id = input_target_id;
        DELETE FROM public.oidc_attempts WHERE account_id = input_target_id;
        UPDATE public.invitations SET revoked_at = changed_at
        WHERE issued_by = input_target_id
          AND consumed_at IS NULL AND revoked_at IS NULL;
        UPDATE public.ingest_credentials
        SET revoked_at = changed_at, generation = generation + 1,
            updated_at = changed_at
        WHERE account_id = input_target_id AND revoked_at IS NULL;
        result := 'disabled';
    END IF;
    INSERT INTO public.account_security_audit
        (occurred_at, actor_account_id, target_account_id, action, outcome)
    VALUES (changed_at, input_actor_id, input_target_id,
            CASE WHEN input_enable THEN 'enable_account' ELSE 'disable_account' END,
            result);
    DELETE FROM public.account_security_audit WHERE id IN (
        SELECT id FROM public.account_security_audit
        WHERE occurred_at < changed_at - interval '365 days'
        ORDER BY occurred_at, id LIMIT 100
    );
    RETURN result;
END
$body$;
REVOKE ALL ON FUNCTION public.admin_set_account_enabled(bigint,bigint,bigint,boolean) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.list_account_security_audit(
    input_actor_id bigint, input_actor_auth_version bigint
) RETURNS TABLE (id bigint, occurred_at timestamptz, actor_account_id bigint,
                 target_account_id bigint, action text, outcome text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
BEGIN
    PERFORM 1 FROM public.accounts a
    WHERE a.id = input_actor_id AND a.is_admin AND a.is_enabled
      AND a.auth_version = input_actor_auth_version FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'audit unavailable' USING ERRCODE = '42501';
    END IF;
    RETURN QUERY SELECT audit.id, audit.occurred_at, audit.actor_account_id,
                        audit.target_account_id, audit.action, audit.outcome
    FROM public.account_security_audit audit
    ORDER BY audit.occurred_at DESC, audit.id DESC LIMIT 50;
END
$body$;
REVOKE ALL ON FUNCTION public.list_account_security_audit(bigint,bigint) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.prune_account_security_audit()
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp
AS $body$
DECLARE
    removed integer;
BEGIN
    DELETE FROM public.account_security_audit WHERE account_security_audit.id IN (
        SELECT audit.id FROM public.account_security_audit audit
        WHERE audit.occurred_at < pg_catalog.clock_timestamp() - interval '365 days'
        ORDER BY audit.occurred_at, audit.id LIMIT 1000
    );
    GET DIAGNOSTICS removed = ROW_COUNT;
    RETURN removed;
END
$body$;
REVOKE ALL ON FUNCTION public.prune_account_security_audit() FROM PUBLIC;

DO $$
BEGIN
    IF to_regclass('odograph_service.managed_role_state') IS NOT NULL THEN
        REVOKE UPDATE (password_hash, is_enabled, auth_version, updated_at,
                       avatar_bytes, avatar_mime, avatar_updated_at)
            ON public.accounts FROM odograph_control;
        REVOKE ALL ON public.accounts FROM odograph_control;
        GRANT SELECT ON public.accounts TO odograph_control;
        GRANT UPDATE (updated_at, avatar_bytes, avatar_mime, avatar_updated_at)
            ON public.accounts TO odograph_control;
        ALTER TABLE public.account_security_audit OWNER TO odograph_migrate;
        REVOKE ALL ON public.account_security_audit
            FROM PUBLIC, odograph_control, odograph_runtime, odograph_bootstrap;
        GRANT SELECT, INSERT, DELETE ON public.account_security_audit TO odograph_bootstrap;
        REVOKE ALL ON SEQUENCE public.account_security_audit_id_seq
            FROM PUBLIC, odograph_control, odograph_runtime, odograph_bootstrap;
        GRANT USAGE ON SEQUENCE public.account_security_audit_id_seq TO odograph_bootstrap;
        ALTER FUNCTION public.admin_set_account_enabled(bigint,bigint,bigint,boolean)
            OWNER TO odograph_bootstrap;
        ALTER FUNCTION public.list_account_security_audit(bigint,bigint)
            OWNER TO odograph_bootstrap;
        ALTER FUNCTION public.prune_account_security_audit()
            OWNER TO odograph_bootstrap;
        GRANT EXECUTE ON FUNCTION public.admin_set_account_enabled(bigint,bigint,bigint,boolean)
            TO odograph_control;
        GRANT EXECUTE ON FUNCTION public.list_account_security_audit(bigint,bigint)
            TO odograph_control;
        GRANT EXECUTE ON FUNCTION public.prune_account_security_audit()
            TO odograph_control;
    END IF;
END $$;
